services:
  movie-finder:
    container_name: movie-finder
    build:
      context: .
      target: movie-finder
    environment:
      - PORT=50051
      - MOVIE_STORE_SERVER_ENDPOINT=movie-store:50051
      - USER_PREFERENCES_SERVER_ENDPOINT=user-preferences:50051
      - RECOMMENDER_SERVER_ENDPOINT=recommender:50051
    ports:
      - 50051:50051
  user-preferences:
    container_name: user-preferences
    build:
      context: .
      target: user-preferences
    environment:
      - PORT=50051
    ports:
      - 50052:50051
  recommender:
    container_name: recommender
    build:
      context: .
      target: recommender
    environment:
      - PORT=50051
    ports:
      - 50053:50051
  movie-store:
    container_name: movie-store
    build:
      context: .
      target: movie-store
    environment:
      - PORT=50051
    ports:
      - 50054:50051
